<!--these div's are only used to build the editing form and are never shown on their own-->
<div class="hidden">

    <div id="1column">
        <div class="formcolumn column1 sortable" data-fieldset-column="1">
            <div class="droppable page fieldset-only" id="formcontainerMainArea">
                <span>DROP FIELDSET HERE</span>
            </div>
        </div>
    </div>

    <div id="2column">
        <div class="col1 formcolumn column1 sortable" data-fieldset-column="1">
            <div class="droppable fieldset-only"><span>DROP FIELDSET HERE</span></div>
        </div>
        <div class="col2 formcolumn column2 sortable" data-fieldset-column="2">
            <div class="droppable fieldset-only"><span>DROP FIELDSET HERE</span></div>
        </div>
    </div>
    <!--========================GENERAL fields========s==============-->
    <div id="generalFormElements" class="formRow">

    </div>
    <div class="hidden" id="editFields">
        <div id="generalEditFields">
            <label for="elementName">Name: </label><input type="text" name="element_name" id="elementName" class="nameEntry"/><br/>

            <label for="validationrule">Validatie:</label>
            <select name="element_validationrule" id="validationrule">

            </select><br/>
            <input type="checkbox" name="element_required" value="1" id="element_required"/>
            <label
                for="element_required"><?php echo $this->__('required'); ?></label><br>
        </div>
        <div id="additionalFields"></div>

        <div id="customHTMLEditField"><br>
            Enter HTML code below<br />
            <textarea name="element_value"></textarea>
        </div>
        <div id="legendEditField">
            <label for="elementValue">Legend: </label><input type="text" name="element_legend" id="elementLegend" class="fieldsetEntry"/><br/>
            <input type="hidden" name="column" id="fieldset-column" class="fieldsetEntry"/>
        </div>
        <div id="placeholderEditField">
            <label>Placeholder: </label><input type="text" id="elementPlaceholder" name="element_placeholder" class="valueEntry"/><br/>
        </div>
        <div id="valueEditField">
            <label>Value: </label><input type="text" name="element_value" class="valueEntry" id="elementValue"/><br/>
        </div>
        <div id="labelEditField">
            <label for="elementLabel">Label: </label><input type="text" name="element_label" id="elementLabel" class="valueEntry"/><br/>
        </div>
        <div id="selectEditField">
            <label for="elementValue">Value: </label><input type="text" value="" name="element_value" id="elementValue" class="valueEntry"/><br/>
            <strong><?php echo $this->__('add dropdown options'); ?></strong><br/>

            <div id="selectoptions">asd</div>
        </div>
        <div id="infoboxEditField">
            <label for="infoTextTitle">Titel: </label><input type="text" value="" name="element_label" id="infoTextTitle" class="valueEntry"/><br/>
            <label for="infoText">Text: </label><textarea name="element_value" id="infoText"></textarea><br/>
        </div>
        <div id="parentDependencyEditField">
            <input type="checkbox" value="1" name="element_parentdependency" id="elementParentDependency"><label
                for="elementParentDependency"><?php echo $this->__('Is dependent on parent element'); ?></label>
        </div>
    </div>
</div>

<form id="sortOrderForm" method="post" class="nonAjax" name="sortOrderForm"
      action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/saveSortOrder") ?>?isAjax=true">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
</form>
<form id="removeElementForm" method="post" class="nonAjax" name="removeElementForm"
      action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/removeElement") ?>?isAjax=true">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
</form>
</div>