<div class="leftcolumn">
    <div id="formElements">
        <strong>Elements</strong>

        <div class="draggable fieldset">
            <!--FIELDSET_START-->
            <div class="box formElement fieldset" id="fieldsetTemplate" data-element-type="fieldset">
                <fieldset class="fieldset">
                    <legend>Fieldset</legend>
                    <div class="sortable">
                        <div class="droppable fieldset-droppable">
                            <span>DROP ELEMENT HERE</span>
                        </div>
                    </div>
                </fieldset>
            </div>
            <!--FIELDSET_END-->
        </div>

        <div class="draggable">
            <!--LABEL START-->
            <div class="box formElement" id="labelFieldTemplate" data-element-type="label">
                <label class="label " name="test">Label</label>
            </div>
            <!--LABEL END-->
        </div>


        <div class="draggable formelement">
            <!--INPUT START-->
            <div class="box formElement" id="textFieldTemplate" data-element-type="text">
                <label class="label">Input field</label>
                <input type="text" name="" value="">
            </div>
            <!--INPUT END-->
        </div>

        <div class="draggable" >
            <!--TEXTAREA START-->
            <div class="box formElement" id="textareaFieldTemplate" data-element-type="textarea">
                <label class="label">Textarea</label>
                <textarea>Textarea</textarea>
            </div>
            <!--TEXTAREA END-->
        </div>

        <div class="draggable" >
            <!--SELECT START-->
            <div class="box formElement" id="selectFieldTemplate" data-element-type="select">
                <label class="label">Dropdown</label>
                <select>
                    <option value="">Placeholder</option>
                </select>
            </div>
            <!--SELECT END-->
        </div>

        <div class="draggable" style="margin:15px 5px;clear:both">
            <!--RADIO START-->
            <div class="box formElement" id="radioFieldTemplate" data-element-type="radio">
                <input type="radio" name="" value="" class="formElement">
                <label>Radiobutton</label>
            </div>
            <!--RADIO END-->
        </div>



        <div class="input-box draggable">
            <!--CHECKBOX START-->
            <div class="box formElement" id="checkboxFieldTemplate" data-element-type="checkbox">
                <input type="checkbox"><label>Checkbox</label>
            </div>
            <!--CHECKBOX END-->
        </div>

        <div class="input-box draggable">
            <!--CUSTOM-HTML START-->
            <div class="box formElement" id="customhtmlFieldTemplate" data-element-type="customhtml">
                <label>Custom html</label>
            </div>
            <!--CUSTOM-HTML END-->
        </div>

        <div class="draggable" style="margin:15px 5px;clear:both">
            <!--GROUP START-->
            <div class="box formElement" id="groupFieldTemplate" data-element-type="group">
                <label>Group</label>
                <div name="group">
                    <div class="droppable">

                    </div>
                </div>
            </div>
            <!--GROUP END-->
        </div>

        <div class="draggable">
            <!-- INFOBOX FIELD START-->
            <div class="box formElement" id="infoboxFieldTemplate" data-element-type="infobox">
                <h3 id="infoboxTitle">Textbox</h3>
                <div class="infotext" id="infoboxText">
                    Donec sem est, malesuada vitae lacus in, tincidunt varius ligula. Aenean eu purus ac dolor porttitor hendrerit. Quisque a tincidunt libero. Donec laoreet neque volutpat, blandit urna id, posuere leo.
                </div>
            </div>
            <!-- INFOBOX FIELD END-->
        </div>


        <!--SPECIAL PRE_DEFINED ELEMENTS-->

        <div class="draggable">
                <div class="box formElement" id="yes-noFieldTemplate" data-element-type="yes-no">
                    <label name="title" class="title_label">B.v. Ja/nee vraag of aanhef</label>

                    <input type="radio" id="radio0" name="radio[]" value="ja"><label for="radio0">ja</label>
                    <input type="radio" id="radio1" name="radio[]" value="nee"><label for="radio1">nee</label>
                </div>

        </div>

        <div class="draggable">
            <div>
                <div class="box dateFieldTemplate formElement" title="date" id="dateFieldTemplate" data-element-type="date">
                    <label for="element-135">Datum</label>
                    <select name="day">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                    </select>
                    <select name="month" class="validate-date-month-nl">
                        <option value="1"></option>
                        <option value="2">February</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                        <option value="7">July</option>
                        <option value="8">August</option>
                        <option value="9">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                    </select>
                    <select name="year">
                        <option value="">----</option>
                        <option value="2015">2015</option>
                        <option value="2014">2014</option>
                        <option value="2013">2013</option>
                        <option value="2012">2012</option>
                        <option value="2011">2011</option>
                        <option value="2010">2010</option>
                        <option value="2009">2009</option>
                        <option value="2008">2008</option>
                        <option value="2007">2007</option>
                        <option value="2006">2006</option>
                        <option value="2005">2005</option>
                        <option value="2004">2004</option>
                        <option value="2003">2003</option>
                        <option value="2002">2002</option>
                        <option value="2001">2001</option>
                        <option value="2000">2000</option>
                        <option value="1999">1999</option>
                        <option value="1998">1998</option>
                        <option value="1997">1997</option>
                        <option value="1996">1996</option>
                        <option value="1995">1995</option>
                        <option value="1994">1994</option>
                        <option value="1993">1993</option>
                        <option value="1992">1992</option>
                        <option value="1991">1991</option>
                        <option value="1990">1990</option>
                        <option value="1989">1989</option>
                        <option value="1988">1988</option>
                        <option value="1987">1987</option>
                        <option value="1986">1986</option>
                        <option value="1985">1985</option>
                        <option value="1984">1984</option>
                        <option value="1983">1983</option>
                        <option value="1982">1982</option>
                        <option value="1981">1981</option>
                        <option value="1980">1980</option>
                        <option value="1979">1979</option>
                        <option value="1978">1978</option>
                        <option value="1977">1977</option>
                        <option value="1976">1976</option>
                        <option value="1975">1975</option>
                        <option value="1974">1974</option>
                        <option value="1973">1973</option>
                        <option value="1972">1972</option>
                        <option value="1971">1971</option>
                        <option value="1970">1970</option>
                        <option value="1969">1969</option>
                        <option value="1968">1968</option>
                        <option value="1967">1967</option>
                        <option value="1966">1966</option>
                        <option value="1965">1965</option>
                        <option value="1964">1964</option>
                        <option value="1963">1963</option>
                        <option value="1962">1962</option>
                        <option value="1961">1961</option>
                        <option value="1960">1960</option>
                        <option value="1959">1959</option>
                        <option value="1958">1958</option>
                        <option value="1957">1957</option>
                        <option value="1956">1956</option>
                        <option value="1955">1955</option>
                        <option value="1954">1954</option>
                        <option value="1953">1953</option>
                        <option value="1952">1952</option>
                        <option value="1951">1951</option>
                        <option value="1950">1950</option>
                        <option value="1949">1949</option>
                        <option value="1948">1948</option>
                        <option value="1947">1947</option>
                        <option value="1946">1946</option>
                        <option value="1945">1945</option>
                        <option value="1944">1944</option>
                        <option value="1943">1943</option>
                        <option value="1942">1942</option>
                        <option value="1941">1941</option>
                        <option value="1940">1940</option>
                        <option value="1939">1939</option>
                        <option value="1938">1938</option>
                        <option value="1937">1937</option>
                        <option value="1936">1936</option>
                        <option value="1935">1935</option>
                        <option value="1934">1934</option>
                        <option value="1933">1933</option>
                        <option value="1932">1932</option>
                        <option value="1931">1931</option>
                        <option value="1930">1930</option>
                        <option value="1929">1929</option>
                        <option value="1928">1928</option>
                        <option value="1927">1927</option>
                        <option value="1926">1926</option>
                        <option value="1925">1925</option>
                        <option value="1924">1924</option>
                        <option value="1923">1923</option>
                        <option value="1922">1922</option>
                        <option value="1921">1921</option>
                    </select>
                </div>
            </div>
        </div>
        <!-- date start>
            <div class="box dateFieldTemplate" id="dateFieldTemplate">
                <label><?php echo $this->__('day'); ?></label>
                <select name="day">
                    <option value=""></option>
                    <?php echo $this->fillDays(); ?>
                </select>
                <label><?php echo $this->__('month'); ?></label>
                <select name="month">
                    <?php echo $this->fillMonths(); ?>
                </select>
                <label><?php echo $this->__('year'); ?></label>
                <select name="year">
                    <option value="">----</option>
                    <?php echo $this->fillYears(); ?>
                </select>
            </div>
             date end-->
    </div>
</div>
</div>