<div class="column2">

    <form name="editForm" id="editFormAttributes" action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/saveForm") ?>">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
        <input type="hidden" id="form_id" name="form_id" value=""/>

        <div class="column">
            <label for="formname">Name:</label><input type="text" name="form_title"/>
        </div>
        <div class="column">
            <strong>Page Template</strong>
            <select name="form_template">
                <option value="1">standard</option>
                <option value="2">Full width</option>
                <option value="3">only Right</option>
            </select>
        </div>

        <div class="column">
            <strong>Form Template</strong>

            <select name="form_subtemplate" id="form_subtemplate_select">
                <option value="1column">1 column</option>
                <option value="2column">2 columns</option>
            </select>
        </div>
        <div class="column">
            <button id="formsubmit" title="Opslaan" type="submit" class="scalable task">
                <span>Opslaan</span>
            </button>
        </div>

    </form>
    <div class="column" id="editFormFieldSuccess">&nbsp;</div>

    <div class="formcontainer" id="page-1">
        <div class="droppable page">

        </div>

    </div>
</div>
<form id="sortOrderForm" method="post" name="sortOrderForm" action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/saveSortOrder") ?>?isAjax=true">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
</form>
<div id="formFieldEditor" class="fieldeditor-section">
    <div id="editForm">
        <strong>Edit element properties</strong>

        <form name="editElement" id="editFormField" action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/saveElement") ?>">
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
            <input type="hidden" name="parent_id" id="parent_id" value="">
            <input type="hidden" id="element_id" name="element_id" value=" "/>
            <input type="hidden" id="element_type" name="element_type" value=" "/>
            <input type="hidden" id="element_sort_order" name="element_sort_order" value=" "/>
            <input type="hidden" id="pagenumber" name="pagenumber" value=" "/>
            <input type="hidden" name="validation" value=" "/>

            <!-- form editing fields are inserted here -->

            <button id="elementSubmit" title="Opslaan" type="submit" class="scalable task">
                <span>Opslaan</span>
            </button>
            <div id="error"></div>

        </form>

    </div>
</div>