<div class="main-content">
<form class="nonAjax" id="formbuilder-form" name="" action="<?php echo Mage::helper("adminhtml")->getUrl("/index/postForm") ?>" method="post">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
    <div class="formtitle"><h2><?php echo $this->getFormTitle();?></h2></div>
bxgvhdhdfghdfhdfgh
    <?php echo $this->publishForm(); ?>

    <div class="formsubmit"><input type="submit" value="submit" name="<?php echo $this->__('submit')?>"/>
</form>
</div>