<div class="rightcolumn">
    <form name="editForm" id="editFormAttributes" action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/saveForm") ?>">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
        <input type="hidden" id="form_id" name="form_id" value=""/>

        <div class="column">
            <label for="formname"><?php echo $this->__('Name');?></label><input type="text" name="form_title"/>
        </div>
        <div class="column">
            <label><?php echo $this->__('Receiver');?></label><input type="text" name="form_receiver" id="form_receiver"/>
        </div>

        <div class="column">
            <label><?php echo $this->__('Form Template');?></label>

            <select name="form_subtemplate" id="'subtemplate-select">
                <option value="1">1 column</option>
                <option value="2">2 columns</option>
            </select>
        </div>

        <div class="column">
            <input id="formsubmit" name="save" value="<?php echo $this->__('Save');?>" type="submit" class="scalable task"/>
        </div>
    </form>

    <div class="column">
        <form method="post" class="nonAjax" action="<?php echo Mage::helper('adminhtml')->getUrl('/adminhtml_index/publishForm'); ?>">
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
            <input type="hidden" name="publish_form_id" id="publish_form_id" value="">
            <button id="formpublish" name="publish" type="submit"><span><?php echo $this->__('Publish'); ?></span></button>
        </form>
    </div>

    <div class="column" id="editFormFieldSuccess">&nbsp;</div>

    <div class="formcontainer" id="page-1">

    </div>

    <div style="float:right" class="btnAddPageWrap">
        <button class="right btnAddpage"><span name="addpage"><?php echo $this->__('Add Page');?></span></button>
    </div>

    <div id="formFieldEditor" class="fieldeditor-section">
        <div id="editForm">
            <strong><?php echo $this->__('Edit element properties');?></strong>

            <form name="editElement" id="editFormField" action="<?php echo Mage::helper("adminhtml")->getUrl("/adminhtml_index/saveElement") ?>">
                <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
                <input type="hidden" name="parent_id" id="parent_id" value="">
                <input type="hidden" name="parent_type" id="parent_type" value="">

                <input type="hidden" id="element_id" name="element_id" value=" "/>
                <input type="hidden" id="element_type" name="element_type" value=" "/>
                <input type="hidden" id="element_sort_order" name="element_sort_order" value=" "/>
                <input type="hidden" id="pagenumber" name="pagenumber" value=" "/>
                <input type="hidden" name="validation" value=" "/>

                <!-- Form editing fields are inserted here -->

                <div id="elementSubmit" class="formRow"><br/>
                    <button id="" title="Opslaan" type="submit" class="scalable task block">
                        <span><?php echo $this->__('Save');?></span>
                    </button>
                </div>
                <div id="error"></div>
            </form>
        </div>
    </div>