<div class="column1">
    <div id="formElements">
        <strong>Elements</strong>

        <div class="draggable fieldset" style="margin:15px 5px;">
            <!--fieldset start-->
            <div class="box" id="fieldsetTemplate">
                <fieldset class="fieldset formElement">
                    <legend>Legend</legend>
                    <div class="sortable">
                        <div class="droppable">

                        </div>
                    </div>
                </fieldset>
            </div>
            <!--fieldset end-->
        </div>
        <div class="draggable" style="margin:15px 5px;">
            <!--input start-->
            <div class="box" id="inputFieldTemplate">
                <label class="label">Voornaam</label>
                <input type="text"/ name="voornaam" class="formElement" value="bas">
            </div>
            <!--input end-->
        </div>
        <div class="draggable" style="margin:15px 5px;">
            <!--textarea start-->
            <div class="box newelement" id="textareaFieldTemplate">
                <label class="label"></label>
                <textarea class="formElement">Textarea</textarea>
            </div>
            <!--textarea end-->
        </div>

        <div class="draggable" style="margin:15px 5px;clear:both">
            <!--select start-->
            <div class="box" id="selectFieldTemplate">
                <label class="label"></label>
                <select class="formElement">
                    <option value="1">First</option>
                    <option value="2">Second</option>
                    <option value="3">Third</option>
                </select>
            </div>
            <!--select end-->
        </div>
        <div class="draggable" style="margin:15px 5px;clear:both">
            <!--radio start-->
            <div class="box">
                <input type="radio" name="" value="" class="formElement"><label class="label"></label>
            </div>
            <!--radio end-->
        </div>
        <div class="input-box draggable">
            <!--checkbox start-->
            <div class="box">
                <input type="checkbox" class="formElement" value="1" name="is_subscribed" id="is_subscribed" checked="checked" autocomplete="off">
            </div>
            <!--checkbox end-->
        </div>
    </div>
</div>
</div>