<div class="column1">
    <div id="formElements">
        <strong>Elements</strong>

        <div class="draggable fieldset" style="margin:15px 5px;">
            <!--fieldset_start-->
            <div class="box" id="fieldsetTemplate">
                <fieldset class="fieldset formElement">
                    <legend>Legend</legend>
                    <div class="sortable">
                        <div class="droppable">

                        </div>
                    </div>
                </fieldset>
            </div>
            <!--fieldset_end-->
        </div>
        <div class="draggable" style="margin:15px 5px;">
            <!--input start-->
            <div class="box" id="textFieldTemplate">
                <label class="label">Voornaam</label>
                <input type="text" name="voornaam" class="formElement" value="bas">
            </div>
            <!--input end-->
        </div>
        <div class="draggable" style="margin:15px 5px;">
            <!--textarea start-->
            <div class="box newelement" id="textareaFieldTemplate">
                <label class="label"></label>
                <textarea class="formElement">Textarea</textarea>
            </div>
            <!--textarea end-->
        </div>

        <div class="draggable" style="margin:15px 5px;clear:both">
            <!--select start-->
            <div class="box" id="selectFieldTemplate">
                <label class="label"></label>
                <select class="formElement">
                    <option value="">Placeholder</option>
                </select>
            </div>
            <!--select end-->
        </div>
        <div class="draggable" style="margin:15px 5px;clear:both">
            <!--radio start-->
            <div class="box" id="radioFieldTemplate">
                <input type="radio" name="" value="" class="formElement"><label class="label"></label>
            </div>

            <!--radio end-->
        </div>
        <div class="input-box draggable">
            <!--checkbox start-->
            <div class="box" id="checkboxFieldTemplate">
                <input type="checkbox" class="formElement" value="1" name="is_subscribed" id="is_subscribed" checked="checked" autocomplete="off">
            </div>
            <!--checkbox end-->
        </div>


        <!--SPECIAL PRE_DEFINED ELEMENTS-->
        <div class="draggable">
            <!-- date start-->
            <div class="box dateFieldTemplate">
                <label><?php echo $this->__('day'); ?></label>
                <select name="day">
                    <option value=""></option>
                    <?php echo $this->fillDays(); ?>
                </select>
                <label><?php echo $this->__('month'); ?></label>
                <select name="month">
                    <?php echo $this->fillMonths(); ?>
                </select>
                <label><?php echo $this->__('year'); ?></label>
                <select name="year">
                    <option value="">----</option>
                    <?php echo $this->fillYears(); ?>
                </select>
            </div>
            <!-- date end-->
        </div>
    </div>
</div>
</div>